apiVersion: v1 
kind: Service
metadata:
  name: user-profile-svc
  labels: 
    app: user-profile
spec:
  selector:
    app: user-profile
  ports:
    - name: java
      protocol: TCP
      targetPort: 8080
      port: 8080
  type: NodePort
  

     
      
